on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Update pom file
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: mvn versions:set -DnewVersion=${RELEASE_VERSION}
      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.VERSION_PAT }}

      - name: Commit Changes
        run: |
          git add pom.xml
          git commit -m "Update version in pom.xml"
      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref }}
