on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Update pom file
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: mvn versions:set -DnewVersion=${{ steps.vars.outputs.tag }}
